---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment
  name: marketplace-be-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment
    spec:
      containers:
        - image: image
          name: deployment
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "25m"