stages:
  - build

dind-build:
  stage: build

  image:
    name: docker:stable
  services:
   - name: docker:dind
     alias: dockerdaemon

  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:test" .
    - docker push "$CI_REGISTRY_IMAGE:test"