apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment
  name: marketplace-be-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment
    spec:
      containers:
      - image: 192.168.110.135:5000/deployment:20
        name: deployment
